version: '3'

vars:
  IMAGE_NAME: kube-dump
  REGISTRY1: devopstales
  REGISTRY2: ghcr.io/devopstales

tasks:
  default:
    desc: "Print Help"
    cmds:
      - "task --list-all"

  # Install dependencies
  install:
    desc: Install Python dependencies with Poetry
    cmds:
      - poetry install

  # Run locally
  run:
    desc: Run kube-dump locally
    deps: [install]
    cmds:
      - poetry run python kube-dump.py {{ .CLI_ARGS }}

  # Run with specific namespaces
  run-ns:
    desc: Run kube-dump for specific namespaces
    deps: [install]
    cmds:
      - poetry run python kube-dump.py dump-namespaces -n {{ .NAMESPACES | default "default" }} {{ .CLI_ARGS }}

  audit:
    desc: "Run pip-audit for vulnerabilities"
    cmds:
      - poetry run pip-audit

  scan:
    desc: "Scan for vulnerabilities with trivy"
    cmds:
      - trivy -q fs . --scanners vuln

  lint:
    desc: "Lint and format code"
    cmds:
      - poetry run isort .
      - poetry run flake8 .
      - poetry run autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place .
      - poetry run black --check .

  format:
    desc: "Format code with black"
    cmds:
      - poetry run isort .
      - poetry run black .

  # Build Docker image (linux/amd64 + linux/arm64)
  docker-build:
    desc: Build multi-arch Docker image
    cmds:
      - docker buildx build
          --platform linux/amd64,linux/arm64
          --tag {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:latest
          --tag {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
          --tag {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:latest
          --tag {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
          --file Dockerfile
          --attest type=sbom
          --sbom=true
          --load .

  # Build and push
  docker-build-push:
    desc: Build and push multi-arch image
    cmds:
      - docker buildx build
          --platform linux/amd64,linux/arm64
          --tag {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:latest
          --tag {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
          --tag {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:latest
          --tag {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
          --file Dockerfile
          --attest type=sbom
          --sbom=true
          --push .

  docker-scan:
    desc: "Scan docker image for vulnerabilities"
    cmds:
      - trivy -q i {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }} --scanners vuln

  docker-sign:
    desc: "Sign kube-dump docker image"
    cmds:
      - cosign sign -y --upload=true --key $HOME/.gnupg/cosign.key {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
      - cosign sign -y --upload=true --key $HOME/.gnupg/cosign.key {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}

  clean:
    desc: "Clean backup directory"
    cmds:
      - rm -rf ./backup
