version: '3'

vars:
  IMAGE_NAME: kube-dump
  REGISTRY1: devopstales
  REGISTRY2: ghcr.io/devopstales

tasks:
  default:
    desc: "Print Help"
    cmds:
      - "task --list-all"

  # Install dependencies
  install:
    desc: Install Python dependencies with Poetry
    cmds:
      - poetry install

  # Run locally
  run:
    desc: Run kube-dump locally
    deps: [install]
    cmds:
      - poetry run python kube-dump.py {{ .CLI_ARGS }}

  # Run with specific namespaces
  run-ns:
    desc: Run kube-dump for specific namespaces
    deps: [install]
    cmds:
      - poetry run python kube-dump.py dump-namespaces -n {{ .NAMESPACES | default "default" }} {{ .CLI_ARGS }}

  audit:
    desc: "Run pip-audit for vulnerabilities"
    cmds:
      - poetry run pip-audit

  scan:
    desc: "Scan for vulnerabilities with trivy"
    cmds:
      - trivy -q fs . --scanners vuln

  lint:
    desc: "Lint and format code"
    cmds:
      - poetry run isort .
      - poetry run flake8 .
      - poetry run autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place .
      - poetry run black --check .

  format:
    desc: "Format code with black"
    cmds:
      - poetry run isort .
      - poetry run black .

  # Build Docker image (linux/amd64 + linux/arm64)
  docker-build:
    desc: Build multi-arch Docker image
    cmds:
      - docker buildx build
          --platform linux/amd64,linux/arm64
          --tag {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:latest
          --tag {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
          --tag {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:latest
          --tag {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
          --file Dockerfile
          --attest type=sbom
          --sbom=true
          --load .

  # Build and push
  docker-build-push:
    desc: Build and push multi-arch image
    cmds:
      - docker buildx build
          --platform linux/amd64,linux/arm64
          --tag {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:latest
          --tag {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
          --tag {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:latest
          --tag {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
          --file Dockerfile
          --attest type=sbom
          --sbom=true
          --push .

  docker-scan:
    desc: "Scan docker image for vulnerabilities"
    cmds:
      - trivy -q i {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }} --scanners vuln

  docker-sign:
    desc: "Sign kube-dump docker image"
    cmds:
      - cosign sign -y --upload=true --key $HOME/.gnupg/cosign.key {{ .REGISTRY1 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}
      - cosign sign -y --upload=true --key $HOME/.gnupg/cosign.key {{ .REGISTRY2 }}/{{ .IMAGE_NAME }}:{{ .VERSION | default "dev" }}

  # Helm tasks
  helm-lint:
    desc: "Lint Helm chart"
    cmds:
      - helm lint ./chart

  helm-template:
    desc: "Render Helm chart templates locally"
    cmds:
      - helm template kube-dump ./chart --namespace kube-dump {{ .CLI_ARGS }}

  helm-package:
    desc: "Package Helm chart"
    cmds:
      - helm package ./chart --destination ./dist

  helm-docs:
    desc: "Generate Helm chart documentation (requires helm-docs)"
    cmds:
      - helm-docs --chart-search-root ./chart --output-file README.md

  helm-install:
    desc: "Install Helm chart locally for testing"
    cmds:
      - helm upgrade --install kube-dump ./chart
          --namespace kube-dump
          --create-namespace
          --set config.clusterName={{ .CLUSTER_NAME | default "test-cluster" }}
          {{ .CLI_ARGS }}

  helm-uninstall:
    desc: "Uninstall Helm chart"
    cmds:
      - helm uninstall kube-dump --namespace kube-dump

  helm-diff:
    desc: "Show diff of Helm chart changes (requires helm-diff plugin)"
    cmds:
      - helm diff upgrade kube-dump ./chart
          --namespace kube-dump
          --set config.clusterName={{ .CLUSTER_NAME | default "test-cluster" }}
          {{ .CLI_ARGS }}

  helm-publish:
    desc: "Publish Helm chart to devopstales/helm-charts repo (gh-pages)"
    dir: chart
    vars:
      CHART_VERSION:
        sh: grep '^version:' Chart.yaml | awk '{print $2}'
    cmds:
      - rm -rf gh-pages-temp .cr-release-packages
      - cr package .
      - git clone -b gh-pages git@github.com:devopstales/helm-charts.git gh-pages-temp
      - cp .cr-release-packages/kube-dump-{{ .CHART_VERSION }}.tgz gh-pages-temp/
      - |
        cd gh-pages-temp
        git config user.name "kube-dump"
        git config user.email "kube-dump@devopstales.io"
        git add .
        git commit -n -m "Update kube-dump chart to {{ .CHART_VERSION }}"
        git push --no-verify origin gh-pages
      - rm -rf gh-pages-temp .cr-release-packages

  clean:
    desc: "Clean backup directory and dist"
    cmds:
      - rm -rf ./backup ./dist
